on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
      pages: write
    concurrency:
      group: release
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm audit signatures
      - run: npm run test
      - uses: actions/configure-pages@v3
      - run: npm run docs
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs"
      - name: Deploy documentation
        id: pages
        uses: actions/deploy-pages@v2
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
